# Automatically generated by tasks/ffi_codegen.rb

# :nodoc: namespace
class XDo

# :nodoc: namespace
module FFILib
  # Constant values extracted from headers.
  module Consts
    XDO_SUCCESS = 0
    XDO_ERROR = 1
    SEARCH_PID = 0x0008
    SEARCH_TITLE = 0x0001
    SEARCH_CLASS = 0x0002
    SEARCH_NAME = 0x0004
    SEARCH_SCREEN = 0x0020
    SEARCH_CLASSNAME = 0x0040
    SEARCH_ONLYVISIBLE = 0x0010
    SIZE_USEHINTS = 1
    SIZE_TO = 0
    SIZE_FROM = 1
  end  # module XDo::FFILib::Consts

  # Status returned by libxdo functions.
  Status = enum [
    :success, Consts::XDO_SUCCESS,
    :error, Consts::XDO_ERROR,
  ]

  # Search directions.
  Direction = enum [
  ]

end  # namespace XDo::FFILib
end  # namespace XDo
